oncampus/mediawiki-skins-Loop

.gitignore, Loop.skin.php, LoopTemplate.php, composer.json, i18n/de.json, i18n/en.json, i18n/qqq.json, skin.json
=> Grundgeruest

LoopTemplate.php
Platzhalter für Export ersetzt
nur sichtbar wenn angemeldet (Rechte für Export)
=> added links for export formats xml and pdf

LoopTemplate.php, resources/styles/loop-common/loop-common.less, resources/styles/loop-oncampus/loop-oncampus.less, resources/styles/loop.less, resources/styles/variables.less
der Linker ist deprecated und muss ersetzt werden.
=> Allg. Bugfixes und Linker-Ersatz

Loop.skin.php, LoopTemplate.php, skin.json
LoopSettings kommen jetzt aus der Datenbank und werden in einem Objekt mit selbem Namen angewandt.
Nur mit Extension-Update benutzen!
=> LoopSettings jetzt in Datenbank

LoopTemplate.php, resources/styles/loop.less
Gilt nur für LOOPs, die geschlossen sind.
=> Hide things from users with no reading permission

LoopTemplate.php
Das User-Objekt, LoopSettings und der LinkRenderer werden z.B. nicht mehr in jeder Funktion aufgerufen, sondern hängen jetzt im Template Objekt $this->user.
=> Aufräumarbeiten

LoopTemplate.php, resources/styles/loop.less
Bitte Extension ebenfalls updaten zum Testen
=> Loop Objects und Exceptions

LoopTemplate.php, resources/styles/loop.less, resources/styles/variables.less
Siehe pull request der Extension
=> Feat looparea

LoopTemplate.php
BITV-Optimierte Links, jetzt mit alt-Tag.
Wenn man sich nur einloggen kann (und kein registrieren möglich ist), wird kein Dropdown, sondern ein Loginbutton angezeigt.
=> Besseres User Menu

resources/js/loop.js, resources/styles/less/abstracts/variables.less, resources/styles/less/base/mediawiki.less, resources/styles/less/components/looparea.less, resources/styles/less/components/loopspoiler.less, resources/styles/less/layout/sidebar.less, resources/styles/loop.less
=> Feat spoiler

Loop.skin.hooks.php, LoopTemplate.php, resources/styles/less/layout/general.less, resources/styles/less/pages/specialpages.less, resources/styles/loop.less, skin.json
=> Literaturverzeichnis (Teil 1)

resources/styles/less/abstracts/variables.less, resources/styles/less/components/loopparagraph.less, resources/styles/less/components/loopsidenote.less, resources/styles/loop.less
Support für loop_paragraph-Tag. Desktop und Mobile Site und PDF.
=> added loop_paragraph tag support for site and pdf

resources/styles/less/abstracts/variables.less, resources/styles/less/components/looparea.less, resources/styles/less/components/loopparagraph.less, resources/styles/less/components/loopsidenote.less, resources/styles/less/components/loopspoiler.less, resources/styles/less/pages/structure.less, resources/styles/loop.less
- Variablen aufgeräumt, Componenten haben nur noch eine gemeinsame Variable statt Vererbungen.
- Inhaltsverzeichnis schicker. Überlegung ob zukünftig Tabellenform und weiteren anzeigbaren Features.
=> added structure and changed css vars

LoopTemplate.php
=> Literaturverzeichnis

LoopTemplate.php
Der Login Button wird nicht angezeigt, wenn ein Wiki geschlossen ist.
=> Dringend: Login-Button

Loop.skin.hooks.php, LoopTemplate.php, resources/js/loop.js, skin.json
Swipe-Gesten für mobile hinzugefügt.
Siehe Oldenburg für Demo.
=> Swipe Functionality 

LoopTemplate.php, package.json, resources/styles/less/pages/bugreport.less, resources/styles/loop.less
Die BugReport-Page hat nun ein Captcha.
Einsehbar bei Oldenburg.
ToDo: Sprachstrings (Englisch+Deutsch vorhanden)
=> Captcha-Support für BugReport-Page

resources/js/loop.js, resources/styles/less/components/loopspoiler.less
=> Fix spoilers

resources/styles/less/base/mediawiki.less, resources/styles/less/pages/structure.less
- Inhaltsverzeichnis: h2 -> Link zu /
- Inhaltsverzeichnis: Sehr lange Titel brechen nun korrekt um
- Abstandsfix für .floatleft, .floatright, .center
=> Fix structurefix

resources/styles/less/components/loopobject.less
https://oncampus-gmbh.atlassian.net/browse/LOOP-31
=> Fix der Größe einer Beschreibung

resources/styles/less/base/mediawiki.less
Changed indentation accordingly
=> #32 - Seiteneinzug anpassen
